#!/usr/bin/env bash
# Build ACS.app and package it as ACS-<arch>.dmg.
#
# Bundles the SwiftUI executable with the Rust helper binaries the app expects
# at a fixed location inside the bundle:
#
#   ACS.app/Contents/MacOS/ACS              SwiftUI executable (swift build -c release)
#   ACS.app/Contents/Helpers/acs-desktop    Rust desktop bridge (cargo --locked)
#   ACS.app/Contents/Helpers/qagent         Rust bus/CLI agent
#   ACS.app/Contents/Helpers/aos            Rust harness
#   ACS.app/Contents/Resources/AppIcon.icns generated by make-icon.swift, if present
#   ACS.app/Contents/Info.plist             macos/Resources/Info.plist
#
# Helper layout is a contract: the app locates Contents/Helpers/acs-desktop by
# that exact path, and acs-desktop resolves qagent/aos as siblings in the same
# Helpers directory. Do not move them.
#
# Signing: nested executables are signed first, then the outer bundle. The
# default is ad-hoc signing (codesign identity "-"). Set ACS_CODESIGN_IDENTITY
# to a configured Developer ID Application identity to sign for distribution;
# notarization is out of scope for this script.
#
# Output (under macos/dist/):
#   ACS-<arch>.dmg         UDZO image containing ACS.app + /Applications symlink
#   ACS-<arch>.dmg.sha256  SHA-256 checksum
#
# Native host architecture only — this script never claims a universal build.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACOS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${MACOS_DIR}/.." && pwd)"

ARCH="$(uname -m)"
APP_NAME="ACS"
HELPERS=(acs-desktop qagent aos)

DIST_DIR="${MACOS_DIR}/dist"
STAGE_DIR="${DIST_DIR}/stage"
APP_DIR="${STAGE_DIR}/${APP_NAME}.app"
DMG_PATH="${DIST_DIR}/${APP_NAME}-${ARCH}.dmg"
SHA_PATH="${DMG_PATH}.sha256"

IDENTITY="${ACS_CODESIGN_IDENTITY:--}"

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "build-dmg.sh only runs on macOS"
command -v cargo >/dev/null || die "cargo not found"
command -v swift >/dev/null || die "swift toolchain not found (install Xcode)"
command -v codesign >/dev/null || die "codesign not found"
command -v hdiutil >/dev/null || die "hdiutil not found"

[[ -f "${REPO_ROOT}/rust/Cargo.toml" ]] || die "rust/Cargo.toml not found"
[[ -f "${MACOS_DIR}/Package.swift" ]] || die "macos/Package.swift not found"
[[ -f "${MACOS_DIR}/Resources/Info.plist" ]] || die "macos/Resources/Info.plist not found"

# --- 1. Rust helpers ---------------------------------------------------------

log "Building Rust helpers (release, locked): ${HELPERS[*]}"
BIN_ARGS=()
for helper in "${HELPERS[@]}"; do
    BIN_ARGS+=(--bin "${helper}")
done
cargo build --release --locked \
    --manifest-path "${REPO_ROOT}/rust/Cargo.toml" \
    "${BIN_ARGS[@]}"

RUST_BIN_DIR="${REPO_ROOT}/rust/target/release"
for helper in "${HELPERS[@]}"; do
    [[ -x "${RUST_BIN_DIR}/${helper}" ]] \
        || die "expected helper binary missing: ${RUST_BIN_DIR}/${helper}"
done

# --- 2. Swift executable -----------------------------------------------------

log "Building Swift package (release)"
swift build -c release --package-path "${MACOS_DIR}"

SWIFT_BIN_DIR="$(swift build -c release --package-path "${MACOS_DIR}" --show-bin-path)"
SWIFT_BIN="${SWIFT_BIN_DIR}/${APP_NAME}"
[[ -x "${SWIFT_BIN}" ]] || die "expected Swift executable missing: ${SWIFT_BIN}"

# --- 3. Assemble ACS.app -----------------------------------------------------

log "Assembling ${APP_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${APP_DIR}/Contents/MacOS" "${APP_DIR}/Contents/Helpers" "${APP_DIR}/Contents/Resources"

cp "${SWIFT_BIN}" "${APP_DIR}/Contents/MacOS/${APP_NAME}"
for helper in "${HELPERS[@]}"; do
    cp "${RUST_BIN_DIR}/${helper}" "${APP_DIR}/Contents/Helpers/${helper}"
    chmod 755 "${APP_DIR}/Contents/Helpers/${helper}"
done
cp "${MACOS_DIR}/Resources/Info.plist" "${APP_DIR}/Contents/Info.plist"

plutil -lint "${APP_DIR}/Contents/Info.plist"

# App icon (optional): generated procedurally by make-icon.swift when present.
ICON_SCRIPT="${MACOS_DIR}/scripts/make-icon.swift"
ICONSET_DIR="${DIST_DIR}/build/AppIcon.iconset"
if [[ -f "${ICON_SCRIPT}" ]]; then
    log "Generating AppIcon.icns via make-icon.swift"
    rm -rf "${ICONSET_DIR}"
    mkdir -p "${ICONSET_DIR}"
    swift "${ICON_SCRIPT}" "${ICONSET_DIR}"
    iconutil -c icns -o "${APP_DIR}/Contents/Resources/AppIcon.icns" "${ICONSET_DIR}"
else
    log "make-icon.swift not present — skipping icon generation"
fi

# --- 4. Code sign: nested executables first, then the bundle -----------------

SIGN_ARGS=(--force --sign "${IDENTITY}")
if [[ "${IDENTITY}" != "-" ]]; then
    SIGN_ARGS+=(--options runtime --timestamp)
fi

log "Signing helpers (identity: ${IDENTITY})"
for helper in "${HELPERS[@]}"; do
    codesign "${SIGN_ARGS[@]}" "${APP_DIR}/Contents/Helpers/${helper}"
done

log "Signing ${APP_NAME}.app (identity: ${IDENTITY})"
codesign "${SIGN_ARGS[@]}" "${APP_DIR}"

codesign --verify --deep --strict --verbose=2 "${APP_DIR}"

if [[ "${IDENTITY}" == "-" ]]; then
    log "NOTE: ad-hoc signed, not notarized — Gatekeeper will warn on first launch."
fi

# --- 5. DMG ------------------------------------------------------------------

log "Creating ${DMG_PATH}"
mkdir -p "${STAGE_DIR}"
ln -sfn /Applications "${STAGE_DIR}/Applications"

rm -f "${DMG_PATH}"
hdiutil create \
    -volname "${APP_NAME}" \
    -srcfolder "${STAGE_DIR}" \
    -ov -format UDZO \
    "${DMG_PATH}"

shasum -a 256 "${DMG_PATH}" > "${SHA_PATH}"

# --- 6. Verify the image: attach, list, detach --------------------------------

log "Verifying DMG (attach/list/detach)"
MOUNT_OUTPUT="$(hdiutil attach -nobrowse -readonly "${DMG_PATH}")"
MOUNT_POINT="$(printf '%s\n' "${MOUNT_OUTPUT}" | tail -1 | sed -E 's/.*[[:space:]](\/Volumes\/.+)/\1/')"
[[ -n "${MOUNT_POINT}" ]] || die "could not determine DMG mount point"

detach_dmg() { hdiutil detach "${MOUNT_POINT}" -quiet || true; }
trap detach_dmg EXIT

ls -la "${MOUNT_POINT}"
[[ -d "${MOUNT_POINT}/${APP_NAME}.app" ]] || die "ACS.app missing inside DMG"
[[ -L "${MOUNT_POINT}/Applications" ]] || die "/Applications symlink missing inside DMG"
plutil -lint "${MOUNT_POINT}/${APP_NAME}.app/Contents/Info.plist" >/dev/null

detach_dmg
trap - EXIT

log "Done."
printf 'app:       %s\n' "${APP_DIR}"
printf 'dmg:       %s\n' "${DMG_PATH}"
printf 'sha256:    %s\n' "${SHA_PATH}"
printf 'arch:      %s (native build — not universal)\n' "${ARCH}"
