// After a run: integrate each accepted task's branch into one checkout, build it, and run the frozen validators there.
// Validators and truth live in bench/ of the checkout that runs the benchmark, never in the agents' workdir.
import { existsSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readBus } from "./bus.mjs";
import { git, mustGit, run } from "./util.mjs";

const IMPLICIT_SCOPE = ["dist/"]; // regenerated by every build, so never "outside scope"

function inScope(file, scope) {
  return [...scope, ...IMPLICIT_SCOPE].some((entry) => (entry.endsWith("/") ? file.startsWith(entry) : file === entry));
}

function taskBranch(workdir, taskId) {
  const result = git(workdir, ["for-each-ref", "--format=%(refname:short)", `refs/heads/qagent/task-${taskId}-*`]);
  return result.stdout.split("\n").filter(Boolean)[0] ?? null;
}

export function integrate({ runDir, runRecord, tasks }) {
  const workdir = join(runDir, "workdir");
  const target = join(runDir, "integrated");
  const bus = readBus(join(runDir, "home", "bus.db"));
  const acceptedAt = (task) => bus.events.filter((event) => event.entity === "task" && Number(event.entityId) === task.id && event.kind === "task_accepted").at(-1)?.seq ?? Infinity;
  const accepted = bus.tasks.filter((task) => task.state === "accepted" && task.key?.startsWith("I")).sort((a, b) => acceptedAt(a) - acceptedAt(b));

  if (existsSync(target)) {
    git(workdir, ["worktree", "remove", "--force", target]);
    rmSync(target, { recursive: true, force: true });
  }
  mustGit(workdir, ["worktree", "add", "--force", "-B", "bench/integrated", target, runRecord.baseSha]);
  git(target, ["config", "user.name", "bench"]);
  git(target, ["config", "user.email", "bench@localhost"]);

  const integration = { buildOk: null, noBranch: [], outsideScope: {}, mergeConflicts: [], distConflictsResolved: [], overlapPairs: [] };
  const changed = {};
  for (const task of accepted) {
    const branch = taskBranch(workdir, task.id);
    if (!branch) { integration.noBranch.push(task.key); continue; }
    const files = git(workdir, ["diff", "--name-only", `${runRecord.baseSha}...${branch}`]).stdout.split("\n").filter(Boolean);
    changed[task.key] = files;
    const scope = tasks.find((candidate) => candidate.id === task.key)?.scope ?? [];
    const outside = files.filter((file) => !inScope(file, scope));
    if (outside.length) integration.outsideScope[task.key] = outside;
    const merged = git(target, ["merge", "--no-ff", "--no-edit", "-m", `bench: merge ${task.key}`, branch]);
    if (merged.code === 0) continue;
    const conflicted = git(target, ["diff", "--name-only", "--diff-filter=U"]).stdout.split("\n").filter(Boolean);
    if (conflicted.length && conflicted.every((file) => file.startsWith("dist/"))) {
      // Generated output: keep the integrated side now, the build below regenerates it.
      const resolved = [["checkout", "--ours", "--", "dist"], ["add", "dist"], ["commit", "--no-edit"]].every((args) => git(target, args).code === 0);
      if (resolved) {
        integration.distConflictsResolved.push(task.key);
        continue;
      }
    }
    git(target, ["merge", "--abort"]);
    integration.mergeConflicts.push({ key: task.key, files: conflicted, ...(conflicted.length ? {} : { error: merged.stderr.trim().split("\n")[0] }) });
  }
  const keys = Object.keys(changed);
  for (let i = 0; i < keys.length; i += 1) {
    for (let j = i + 1; j < keys.length; j += 1) {
      const shared = changed[keys[i]].filter((file) => changed[keys[j]].includes(file) && !file.startsWith("dist/"));
      if (shared.length) integration.overlapPairs.push({ a: keys[i], b: keys[j], files: shared });
    }
  }
  return { integration, target };
}

function buildCheckout(target, workdir) {
  const modules = join(workdir, "node_modules");
  if (existsSync(modules) && !existsSync(join(target, "node_modules"))) symlinkSync(modules, join(target, "node_modules"), "dir");
  const tsc = join(target, "node_modules", "typescript", "bin", "tsc");
  if (!existsSync(tsc)) return false;
  return run(process.execPath, [tsc], { cwd: target }).code === 0;
}

export function runValidators({ target, runRecord, tasks, timeoutMs = 10 * 60_000 }) {
  const results = {};
  for (const task of tasks.filter((candidate) => candidate.kind === "implementation" && runRecord.taskKeys.includes(candidate.id))) {
    const started = Date.now();
    const result = run(process.execPath, [join(runRecord.benchRoot, task.validator)], {
      cwd: target, timeout: timeoutMs,
      env: { ...process.env, BENCH_CHECKOUT: target, BENCH_BASE_SHA: runRecord.baseSha, BENCH_TASK: task.id },
    });
    const tail = `${result.stdout}${result.stderr}`.trim().split("\n").slice(-12).join("\n");
    results[task.id] = { passed: result.code === 0, exitCode: result.code, ms: Date.now() - started, output: tail };
  }
  return results;
}

export function validateReal({ runDir, runRecord, tasks, build = true }) {
  let target = join(runDir, "workdir");
  let integration = null;
  if (runRecord.isolation === "worktree") {
    ({ integration, target } = integrate({ runDir, runRecord, tasks }));
  }
  const buildOk = build ? buildCheckout(target, join(runDir, "workdir")) : null;
  if (integration) integration.buildOk = buildOk;
  const validators = runValidators({ target, runRecord, tasks });
  writeFileSync(join(runDir, "validators.json"), `${JSON.stringify(validators, null, 2)}\n`);
  if (integration) writeFileSync(join(runDir, "integration.json"), `${JSON.stringify(integration, null, 2)}\n`);
  return { validators, integration, buildOk };
}

/** Fake runs change no files, so validator outcomes come from the script instead. */
export function validateFake({ runDir, runRecord, tasks, script }) {
  const validators = {};
  for (const task of tasks.filter((candidate) => candidate.kind === "implementation" && runRecord.taskKeys.includes(candidate.id))) {
    validators[task.id] = { passed: script.tasks?.[task.id]?.validator !== "fail", fake: true };
  }
  writeFileSync(join(runDir, "validators.json"), `${JSON.stringify(validators, null, 2)}\n`);
  return { validators };
}
